server1_hostname: 172.18.18.203
server2_hostname: 172.18.18.100
server3_hostname: 172.18.18.101
server4_hostname: 172.18.18.102
zk_cluster: 172.18.18.101:2181,172.18.18.100:2181,172.18.18.203:2181
bootstrap_servers: 172.18.18.203:9092,172.18.18.100:9092,172.18.18.101:9092,172.18.18.102:9092
ES_MEM: 500M
cluster_name: hbase2es-cluster
master_ip: 172.18.18.203
node_master: s203
cluster_master: "172.18.18.203"
cluster_f1: "172.18.18.100"
cluster_f2: "172.18.18.101"
cluster_f3: "172.18.18.102"
BigdataDir: /opt/hzgc
namenode1_hostname: 172.18.18.203
namenode2_hostname: 172.18.18.100
tidb_hostname: 172.18.18.203
tidb_password: Hzgc@123
AnsibleDir: /opt/ansible
GosunBigDataDir: /opt/GosunBigDataDeploy/docker-compose
